#!/bin/sh
# ══════════════════════════════════════════════════════════════
# DC Manager Pro — Netdata container entrypoint
#
# Writes /etc/netdata/stream.conf with the actual API key
# from the NETDATA_STREAM_API_KEY environment variable,
# then starts Netdata normally.
#
# This is needed because Netdata does NOT substitute
# shell-style ${VAR} references in its config files.
# ══════════════════════════════════════════════════════════════

set -e

# Validate key
if [ -z "$NETDATA_STREAM_API_KEY" ] || [ "$NETDATA_STREAM_API_KEY" = "CHANGE-THIS-STREAM-KEY" ]; then
    echo "WARNING: NETDATA_STREAM_API_KEY is not set or is still the default."
    echo "         Child nodes will NOT be able to connect until you:"
    echo "         1. Set NETDATA_STREAM_API_KEY=<uuid> in your .env"
    echo "         2. Run: docker restart dcm_netdata"
    echo ""
fi

# Write stream.conf with the real key
cat > /etc/netdata/stream.conf << STREAMCONF
# Auto-generated by netdata-entrypoint.sh — do not edit manually.
# Edit NETDATA_STREAM_API_KEY in /appdata/dc-prod/.env and restart.

# Outgoing streams — disabled on this parent node
[stream]
    enabled = no

# Accept incoming streams authenticated with this API key
[$NETDATA_STREAM_API_KEY]
    enabled                = yes
    allow from             = 10.* 172.* 192.168.* localhost
    default memory mode    = dbengine
    default history        = 86400
    health enabled by default = auto
STREAMCONF

echo "Netdata: stream.conf written with API key: ${NETDATA_STREAM_API_KEY}"

# Hand off to the real Netdata entrypoint
exec /usr/sbin/run.sh "$@"
